title: vLLM Blog
author:
  name: Â© 2025. vLLM Team. All rights reserved.
google_analytics: G-9C5R3JR3QS
url: https://blog.vllm.ai

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  vLLM is a fast and easy-to-use library for LLM inference and serving.

# Build settings

remote_theme: jekyll/minima@5ce4006d175e6e5278bb63a0aad1a85e3bf2370b

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Theme-specific settings

minima:
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  social_links:
    - title: vLLM repository on GitHub
      icon: github
      url: "https://github.com/vllm-project/vllm"
    - title: vLLM on X (formerly Twitter)
      icon: x-twitter
      url: "https://x.com/vllm_project"
    - title: vLLM on LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/company/vllm-project"
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=qc6CJjYAAAAJ" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#
header_pages:
  - index.md

# Set to `true` to show excerpts on the homepage.
#
# show_excerpts: false
