title: vLLM Blog
author:
  name: Â© 2025. vLLM Team. All rights reserved.
google_analytics: G-9C5R3JR3QS
url: https://blog.vllm.ai
logo: /assets/logos/vllm-logo-only-light.png

description: >
  vLLM is a fast and easy-to-use library for LLM inference and serving.

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gfm-admonitions

# Social links for footer
social_links:
  - title: GitHub
    url: "https://github.com/vllm-project/vllm"
    icon: github
  - title: X
    url: "https://x.com/vllm_project"
    icon: x
  - title: LinkedIn
    url: "https://www.linkedin.com/company/vllm-project"
    icon: linkedin

# Excerpt settings
excerpt_separator: <!--more-->
